- hosts: localhost
  become: true
  tasks:
    - name: Install htop with dnf
      dnf: name=htop
      when: ansible_os_family == "RedHat"

    - name: Install htop with apt
      apt: name=htop
      when: ansible_os_family == "Debian"

    - name: DNF update system
      dnf:
        name: "*"
        state: latest
      when: ansible_distribution == 'Red Hat Enterprise Linux' or ansible_distribution == 'Fedora'

    - name: Reboot required
      command: "/usr/bin/needs-restarting -r"
      register: reboot_required
      ignore_errors: True
      changed_when: False
      failed_when: reboot_required.rc == 2
      when: ansible_os_family == "RedHat"

    - name: check for reboot file
      stat:
      path: /var/run/reboot-required
      register: reboot_required_file
      when: ansible_os_family == "Debian"

    - name: rebooting
      command: shutdown -r +1
      when: (ansible_os_family == "Debian" and reboot_required_file.stat.exists) or (ansible_os_family == "RedHat" and reboot_required.rc == 1)
